---
# name of the host/instance/vm
- hosts: all
# admin access to install any dependencies
  become: yes
# collect logs or gather facts
  gather_facts: yes
  tasks:
  - name: "Populate service facts"
# Gathers service state information of all the available services as fact data
    service_facts:
  - name: "Check the service nginx facts as they are"
# Specifically filters out the state of nginx service and displays it on the console
    debug:
      msg: "{{ansible_facts.services['nginx.service'].state}}"
  - name: "Verify if nginx is running!"
# Asserts that nginx service is running in all hosts and prints a message on the console depending on its status
    assert:
      that:
        - "'{{ansible_facts.services['nginx.service'].state}}' == 'running'"
      fail_msg: "nginx is down, please check nginx status or restart!"
      success_msg: "no issues, service is running as expected"
